### PR TITLE
put auto-redirect in place for https://hpcugent.github.io/easybuild to https://easybuilders.github.io/easybuild

### PR DESCRIPTION
**Pull request by boegel**
Please wait until the EasyBuild repositories have actually been moved to https://github.com/easybuilders (planned for Wed July 5th 2017).

### CODE REVIEW

**Comment by JensTimmerman** [comment]
lgtm, probably wont' work as long as EB repo is still in place, or the other way around.

**Comment by boegel** [comment]
@JensTimmerman Well, let's not tempt fate and merge it before https://github.com/hpcugent/easybuild has been moved to https://github.com/easybuilders/easybuild :)

**Comment by boegel** [comment]
I included a copy of distribute-0.6.49-patched1.tar.gz to avoid breaking existing copies of the EasyBuild bootstrap script (which is being updated in https://github.com/easybuilders/easybuild-framework/pull/2256 to use the new location instead).

**Comment by boegel** [comment]
http://hpcugent.github.io/easybuild/ is broken now, so merging this to put redirect to http://easybuilders.github.io/easybuild/ in place...

**Pull request merged**
